apiVersion: v1 # version of Kubernetes API
kind: Secret # define a Secret object
metadata: # define metadata for the Secret object
  name: mongodb-secret # sets the name of the Secret object as "mongodb-secret"
stringData: # sets the string data for the Secret object
  MONGO_ROOT_USERNAME: admin # sets the string data "MONGO_ROOT_USERNAME" to the value "admin"
data: # sets the data for the Secret object
  MONGO_ROOT_PASSWORD: c3VwZXJzZWNyZXRwYXNzd29yZA== # sets the data "MONGO_ROOT_PASSWORD" to the value "c3VwZXJzZWNyZXRwYXNzd29yZA==" (base64 encoded string of "supersecretpassword")
