apiVersion: apps/v1 # Version of Kubernetes API
kind: Deployment # Define the Deployment object
metadata: # Define metadata for the Deployment
  name: shipping-service # Set the name of the Deployment as "shipping-service"
  labels: # Define labels for the Deployment
    app: shipping # Set the label "app" as "shipping"
spec: # Define the specification for the Deployment
  replicas: 1 # Set the number of replicas to 1
  selector: # Define the selector for the Deployment
    matchLabels: # Define the labels for the selector
      app: shipping # Set the label "app" as "shipping"
  template: # Define the template for the Deployment
    metadata: # Define metadata for the template
      labels: # Define labels for the template
        app: shipping # Set the label "app" as "shipping"
    spec: # Define the specification for the template
      containers: # Define the containers for the template
      - name: shipping-service # Set the name of the container as "shipping-service"
        image: ghcr.io/thedaamanda/shipping-service:latest # Set the image of the container
        imagePullPolicy: IfNotPresent # Set the image pull policy to "IfNotPresent"
        ports: # Define the ports exposed by the container
        - containerPort: 3001 # Set the port number to 3001
        env: # Define the environment variables for the container
          - name: AMQP_URL # Set the name of the environment variable as "AMQP_URL"
            value: amqp://10.98.115.21:5672 # Set the value of the environment variable
